### ISSUE TITLE
idea: running the proxy without blocking the calling thread

### ISSUE THREAD

**Issue by yanns** [hjr3/alacrity#11]
It'd be great to be able to control how to start a proxy. I see 2 modes:
- starting the proxy blocks the calling thread.
- starting the proxy does not block the calling thread. We may use another thread for that. In that case, we should be able to stop the proxy.

API idea:
```rust
let proxy = Proxy::new(/* ... */);
proxy.listen(); // blocks the main thread
```

```rust
let proxy = Proxy::new(/* ... */);
let startedProxy = proxy.start(); // does not block the main thread
// .....
startedProxy.stop();
```

**Comment by hjr3** [comment]
This is a good idea. I am about to put up a PR for pool management that does not block the calling thread. Once that lands, we can make this happen.

**Comment by hjr3** [comment]
Spoke with Carl about how to do this in tokio:

> [19:37:12]  <hjr3>	is there a way to "interrupt" listener.incoming().foreach() ? i have not found a solution when reading through future-rs and tokio-core
> [19:43:22]  <carllerche>	Select on a signal?
> [19:47:02]  <hjr3>	that was my first thought. i guess i need to do something like convert the stream into a stream future, select on that and then convert the future back into a stream?
> [19:48:19]  <carllerche>	There could be a combinator 
> [19:48:45]  <carllerche>	Is there a take_until(future)?
> [19:49:31]  <hjr3>	not that i see
> [19:50:02]  <carllerche>	It shouldn't be too hard to impl 
> [19:50:06]  <hjr3>	ya i can give it a shot
> [19:50:26]  <carllerche>	Take a Future<Item=()>
> [19:50:33]  <carllerche>	Errors will probably have to match 
> [19:50:59]  <carllerche>	And it yields a new stream that has the values until the future completes 
> [19:51:22]  <hjr3>	ok

**Comment by hjr3** [comment]
note that https://github.com/tokio-rs/tokio-proto/blob/e42b3bfbf5f35402feb595363f42fcba4ef14079/src/tcp_server.rs is probably where this PR should land.

**Comment by mitchtbaum** [comment]
Could [tokio-pool](https://github.com/Connorcpu/tokio-pool/) help with this?

**Comment by hjr3** [comment]
@mitchtbaum we need a way to cancel `listener.incoming().for_each()`. I believe we need to get a PR into futures-rs that implements `take_until` on a stream and then have tokio-proto and/or tokio-pool use `take_until` when listening for incoming connections.

**Comment by hjr3** [comment]
Should be fixed in https://github.com/hjr3/alacrity/pull/53 which should land soon.
