### ISSUE TITLE
idea: let the proxy picks up one free port

### ISSUE THREAD

**Issue by yanns** [hjr3/alacrity#12]
We could start a proxy listening on port 0.
In that case, the kernel would pick up a free port for us.
We need some API to access the port the proxy is listening on.

**Comment by hjr3** [comment]
If we implement #11, then we will have an object that will allow us to implement something similar to the way hyper works.

**Comment by hjr3** [comment]
Should be fixed in https://github.com/hjr3/alacrity/pull/53 which should land soon.
