### ISSUE TITLE
Properly serialize request for backend

### ISSUE THREAD

**Issue by hjr3** [hjr3/alacrity#15]
In `src/backend.rs` the request is (mostly) hard coded. We should honor what the client is sending in.

One of the things I was thinking of was "Why are we parsing a request and then serializing that same request back"? One of the reasons we might want to do that is if we allow modification of the incoming request, such as adding or modifying header. Even in that case, we might decide modify the bytes.

**Comment by yanns** [comment]
I asked myself exactly the same questions, and came to the same tradeoffs... 😉

**Comment by hjr3** [comment]
Fixed in https://github.com/hjr3/alacrity/pull/29
