### ISSUE TITLE
handle chunked request body

### ISSUE THREAD

**Issue by yanns** [hjr3/alacrity#32]
For the moment, we only support request body when the body is directly available, with a `Content-Length` header.

We should support also chunked request body, send with the `Transfer-Encoding` http header.

**Comment by hjr3** [comment]
@yanns This was resolved in #43, correct?

**Comment by yanns** [comment]
I guess yes, although I have not tested that.
Have you tested it?

**Comment by hjr3** [comment]
No, let's leave this open until we get tests in https://github.com/hjr3/alacrity/blob/master/tests/test-proxy.rs
