### ISSUE TITLE
Retry policy when a backend fail

### ISSUE THREAD

**Issue by yanns** [hjr3/alacrity#48]
When a backend cannot answer a request, we can retry this request on another backend.

- per default we should only retry requests without side-effects (only GET?)
- we can define a back off policy. A good default can be https://en.wikipedia.org/wiki/Exponential_backoff#Binary_exponential_backoff_.2F_truncated_exponential_backoff
- we can define the maximal number of retries
- we can define the maximal period of time we can retry (time between request received and now)

**Comment by hjr3** [comment]
Similar to #23

**Comment by yanns** [comment]
right

**Comment by hjr3** [comment]
We can leave it open. I wanted to link the two convos 😄
